### ISSUE TITLE
Install R packages into renv cache during container build

### ISSUE THREAD

**Issue by MiguelRodo** [MiguelRodo/DevContainerFeatures#42]
For apptainer, the cache will likely need to be non-writeable (unless it's copied upon container creation to a writeable path), so an specify multiple cache paths, and which ones to write to: https://github.com/rstudio/renv/issues/1946#issuecomment-2261581214

May help with #30 

We could also install the latest packages into `/usr/local/lib/R/library`, as that's the system library used by `renv`:

![image](https://github.com/user-attachments/assets/ec4a6d12-8e9a-4437-ac32-2b82b1379c82)

Even when we're not using project profiles:

![image](https://github.com/user-attachments/assets/2328f1ae-9281-4ff7-b2bc-3ffb2a9e9ab1)

**Comment by MiguelRodo** [comment]
I'm having two difficulties:

- Getting access to the .devcontainer folder
  - It is not mounted during the container build process (when `Codespaces` is creating it).
    - Well, I don't think so. Worth checking (perhaps `ls /` and, if `/workspaces` exists, run `ls /workspaces` during container buil dprocess
- Getting access to authentication token
  - This is a problem if:
    - We want to install from private repos (can disable manually, at the moment; don't want to do this anyway; would be good to auto-check if they are private first)
    - We do not have access to the `.devcontainer` folder.
    
So, if it's a problem during the codespaces build process, we have the following options:

## Only install `R` packages as prebuilds done using GHA

Here is the relevant part of the `devcontainer-build.yml` file:

```yml

    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase image name
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Debug IMAGE_NAME
        run: |
          echo "IMAGE_NAME is set to: $IMAGE_NAME"
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}

      - name: Pre-build dev container image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.IMAGE_NAME }}
          cacheFrom: ${{ env.IMAGE_NAME }}
```

We'd need to make the following changes:

- (Possibly) allow overriding GITHUB_TOKEN with GH_TOKEN, if supplied
- Be able to figure out which `devcontainer.json` file we want (by default, probably just .devcontainer/devcontainer.json`.
- Run additional commands in the `devcontainers/ci@v0.3` build GHA
